Update Makefile

diff --git a/src/rtsmart/Makefile b/src/rtsmart/Makefile
--- a/src/rtsmart/Makefile
+++ b/src/rtsmart/Makefile
@@ -26,6 +26,11 @@ endif
 	cp -f $(SDK_SRC_ROOT_DIR)/include/generated/autoconf.h $(SDK_RTSMART_SRC_DIR)/rtsmart/kernel/bsp/maix3/k_autoconf_comm.h; \
 	$(SDK_RTSMART_SRC_DIR)/parse_config || exit $?; \
 	cd $(SDK_RTSMART_SRC_DIR)/rtsmart/kernel/bsp/maix3; \
+	if [ ! -f configs/${SDK_DEFCONFIG} ]; then \
+		echo "Error: Configuration file '${SDK_DEFCONFIG}' not found."; \
+		echo "Please ensure that '${SDK_DEFCONFIG}' exists in the 'configs' directory."; \
+		exit 1; \
+	fi; \
 	rm -rf rtconfig.h; \
 	scons --useconfig=configs/${SDK_DEFCONFIG} || exit $?; \
 	cd -; \
